const booksData = [
    {
        id: 1,
        name: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        rating: '4.28',
        description: 'A classic novel exploring themes of racial injustice and moral growth in the American South during the 1930s.',
        imageUrl: 'https://m.media-amazon.com/images/I/71smIoGNeiL._AC_UY218_.jpg',
    },
    
    {
        id: 2,
        name: '1984',
        author: 'George Orwell',
        rating: '4.55',
        description: 'A dystopian novel that warns of the dangers of totalitarianism and government surveillance.',
        imageUrl: 'https://m.media-amazon.com/images/I/71XC83pge-L._AC_UY218_.jpg',
    },
    {
        id: 3,
        name: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        rating: '3.8',
        description: 'A coming-of-age novel that follows the adventures of a young man named Holden Caulfield in New York City.',
        imageUrl: 'https://m.media-amazon.com/images/I/71-gnsG9dVL._AC_UY218_.jpg',
    },
    {
        id: 4,
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        rating: '4.27',
        description: 'A beloved classic novel that explores themes of love, marriage, and social class in 19th-century England.',
        imageUrl: 'https://m.media-amazon.com/images/I/71GOD1Bl-jL._AC_UY218_.jpg',
    },
    {
        id: 5,
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        rating: '4.27',
        description: 'A beloved classic novel that explores themes of love, marriage, and social class in 19th-century England.',
        imageUrl: 'https://m.media-amazon.com/images/I/71GOD1Bl-jL._AC_UY218_.jpg',
    },
    {
        id: 6,
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        rating: '4.27',
        description: 'A beloved classic novel that explores themes of love, marriage, and social class in 19th-century England.',
        imageUrl: 'https://m.media-amazon.com/images/I/71GOD1Bl-jL._AC_UY218_.jpg',
    },
    {
        id: 4,
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        rating: '4.27',
        description: 'A beloved classic novel that explores themes of love, marriage, and social class in 19th-century England.',
        imageUrl: 'https://m.media-amazon.com/images/I/71GOD1Bl-jL._AC_UY218_.jpg',
    },
    {
        id: 7,
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        rating: '4.27',
        description: 'A beloved classic novel that explores themes of love, marriage, and social class in 19th-century England.',
        imageUrl: 'https://m.media-amazon.com/images/I/71GOD1Bl-jL._AC_UY218_.jpg',
    },
    {
        id: 8,
        name: 'Pride and Prejudice',
        author: 'Jane Austen',
        rating: '4.27',
        description: 'A beloved classic novel that explores themes of love, marriage, and social class in 19th-century England.',
        imageUrl: 'https://m.media-amazon.com/images/I/71GOD1Bl-jL._AC_UY218_.jpg',
    },
];

export default booksData;